### ISSUE TITLE
[Fixed] Incompatibility with BizHawk 2.10

### ISSUE THREAD

**Issue by xDrHellx** [xDrHellx/Bok-Interface#29]
When trying to load a release it's just greyed out and when trying to build using BizHawk 2.10-rc2, the build fails with an error.
It seems that the API.cs file needs an update, as some BizHawk internal methods and properties have been changed.

```
E:\Bok-Interface\BokInterface>dotnet build
  Determining projects to restore...
  All projects are up-to-date for restore.
E:\Bok-Interface\BokInterface\all\APIs.cs(48,21): warning CS8602: Dereference of a possibly null reference. [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\APIs.cs(70,21): error CS7036: There is no argument given that corresponds to the required parameter 'ioa' of 'LoadRomArgs.LoadRomArgs(IOpenAdvanced, bool?)' [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\APIs.cs(70,35): error CS0191: A readonly field cannot be assigned to (except in a constructor or init-only setter of the type in which the field is defined or a variable initializer) [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\CheckGroupBox.cs(12,36): warning CS0067: The event 'CheckGroupBox.CheckedChanged' is never used [E:\Bok-Interface\BokInterface\BokInterface.csproj]

Build FAILED.

E:\Bok-Interface\BokInterface\all\APIs.cs(48,21): warning CS8602: Dereference of a possibly null reference. [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\CheckGroupBox.cs(12,36): warning CS0067: The event 'CheckGroupBox.CheckedChanged' is never used [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\APIs.cs(70,21): error CS7036: There is no argument given that corresponds to the required parameter 'ioa' of 'LoadRomArgs.LoadRomArgs(IOpenAdvanced, bool?)' [E:\Bok-Interface\BokInterface\BokInterface.csproj]
E:\Bok-Interface\BokInterface\all\APIs.cs(70,35): error CS0191: A readonly field cannot be assigned to (except in a constructor or init-only setter of the type in which the field is defined or a variable initializer) [E:\Bok-Interface\BokInterface\BokInterface.csproj]
    2 Warning(s)
    2 Error(s)

Time Elapsed 00:00:03.95
```

**Comment by xDrHellx** [comment]
This has been fixed in a separate branch. This branch will be merged when BizHawk 2.10 is officially released (as i'm writing this, it's still only a pre-release).

https://github.com/xDrHellx/Bok-Interface/commit/af502d83c9f9ed83f251140f99e01cde5178663b
